Added in grid view in filebrowser
threefoldtech/twin_aydo pull request #141
Opened 2021-10-05 12:31 UTC by bertmeeuws

2021-10-05 13:18 UTC, JonasWijne reviewed
this merge conflict is bad please checkl first before comming back to me

2021-10-05 13:18 UTC, JonasWijne commented on index.html
> +        <link rel="icon" href="/logo_no_stroke.png" />
weird

2021-10-05 13:18 UTC, JonasWijne commented on public/config/version.ts
> +export default '{{version}}';
```suggestion
export default "{{version}}";
```

2021-10-05 13:18 UTC, JonasWijne commented on public/config/version.ts
> +export default '{{version}}';
not necessary

2021-10-05 13:18 UTC, JonasWijne commented on .prettierrc
> +    "trailingComma": "es5",
whitespace => pls change

2021-10-05 13:18 UTC, JonasWijne commented on README.md
> +-   chat interface
whitespace

2021-10-05 13:18 UTC, JonasWijne commented on index.html
> +        <link rel="icon" href="/logo_no_stroke.png" />
?

2021-10-05 13:18 UTC, JonasWijne commented on index.html
> +        <link href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" rel="stylesheet" />
?

2021-10-05 13:18 UTC, JonasWijne commented on index.html
> -                >We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't
?

2021-10-05 13:18 UTC, JonasWijne commented on index.html
> +                enabled. Please enable it to continue.</strong
?

2021-10-05 13:18 UTC, JonasWijne commented on public/config/config.js
> +import config from '/config/config.json' assert { type: 'json' };
?

2021-10-05 13:18 UTC, JonasWijne commented on public/config/config.js
> +config.baseUrl = `${window.location.origin}/`;
?

2021-10-05 13:18 UTC, JonasWijne commented on public/config/config.js
> +window.config = config;
?

2021-10-05 13:18 UTC, JonasWijne commented on public/config/config.json
> -
unnecessary

2021-10-05 13:18 UTC, JonasWijne commented on src/assets/index.css
> +    th {
?

2021-10-05 13:18 UTC, JonasWijne commented on src/components/AudioPlayer.vue
> +    <div class="flex items-center p-2 pb-6">
what is standard: make ticket to check all files follow up with project lead

2021-10-05 13:18 UTC, JonasWijne commented on src/components/AudioPlayer.vue
> +            class="
what is standard: make ticker to check all files

2021-10-05 13:18 UTC, JonasWijne commented on src/components/AudioPlayer.vue
> +            <PauseIcon aria-hidden="true" class="h-5 w-5" />
?

2021-10-05 13:18 UTC, JonasWijne commented on src/components/AudioPlayer.vue
> +            class="
?

2021-10-05 13:18 UTC, JonasWijne commented on src/components/AudioPlayer.vue
> +            @click="isPlaying = true"
?

2021-10-05 13:18 UTC, JonasWijne commented on src/components/Button.vue
> +    <button
why did you add this file please make sure you do git add with `git add -p`

2021-10-05 13:18 UTC, JonasWijne commented on src/components/ChatCard.vue
> +        <div class="place-items-center relative">
?

2021-10-05 13:20 UTC, JonasWijne commented
commit messages not specific enough

2021-10-05 13:56 UTC, bertmeeuws commented
- Adding hovers on sidebars and modals
- Added cleaner looking exit button in modal
- Clicking outside of the modal will exit it
- ESCAPE key in modal will also exit it
- Using a "/" in a folder name will give real time feedback
- Added an error when a has no name
- Added a max. char length of 50 in a folder name
- When a file is now dragged into the fileuploader it doesn't reset, it takes the exisiting files in the array and adds the new one
- Put in error saying you need atleast one file when trying to upload if none are chosen
- Added a small fix for when /quantum is loaded but the directory isn't set to '/'
- Added grid mode for local filebrowser and shared with me folder
- Refactored the navigation in ContactAdd.vue to reading it out from an array and not hardcoded.
- You can now unselect folders/files by clicking the gray area

![image](https://user-images.githubusercontent.com/56439373/136036632-fc1aa48c-1018-4890-978c-78e5c9f7fd99.png)

![image](https://user-images.githubusercontent.com/56439373/136036722-e89c7b09-d655-425d-b5bb-36014c977c53.png)

![image](https://user-images.githubusercontent.com/56439373/136036753-18fd5676-d09d-439a-9c9b-f933cbf6512c.png)

![image](https://user-images.githubusercontent.com/56439373/136037315-cff65b9c-8b14-42e1-9ed1-6918fc9224aa.png)

2021-10-05 14:00 UTC, JonasWijne reviewed
too much unnecessary changes

2021-10-05 14:07 UTC, bertmeeuws commented on src/components/ChatCard.vue
> +        class="
Added a hover & duration

2021-10-05 14:07 UTC, bertmeeuws commented on src/components/ChatList.vue
> +                            duration:300
Added a hover & duration

2021-10-05 14:08 UTC, bertmeeuws commented on src/components/ContactAdd.vue
> +                v-for="item in navigation"
Navigation is now read out from an array

2021-10-05 14:09 UTC, bertmeeuws commented on src/components/ContactAdd.vue
> +                        duration-300
Added a hover & duration

2021-10-05 14:10 UTC, bertmeeuws commented on src/components/Dialog.vue
> +                            bg-transparent
- Added a circle around the exit button in a modal
- Added a hover & duration

2021-10-05 14:10 UTC, bertmeeuws commented on src/components/Dialog.vue
> +                            duration-300
Added a hover & duration

2021-10-05 14:10 UTC, bertmeeuws commented on src/components/Sidebar.vue
> +                    'cursor-pointer transition duration-300 hover:bg-primarylight rounded-xl': app.enabled,
Added a hover & duration

2021-10-05 14:10 UTC, bertmeeuws commented on src/components/UserTable.vue
> +                                                duration-300
Added a hover & duration

2021-10-05 14:10 UTC, bertmeeuws commented on src/components/UserTableGroup.vue
> +                                                    transition
Added a hover & duration

2021-10-05 14:12 UTC, bertmeeuws commented on src/components/fileBrowser/FileTable.vue
> +                    <FileDropArea @click.stop class="h-full" @send-file="uploadFiles">
Added a @click.stop to propagate the "deselect all files by clicking the gray background" when clicking around in the filebrowser itself

2021-10-05 14:12 UTC, bertmeeuws commented on src/components/fileBrowser/FileTable.vue
> +                        <ul
This is the new grid view

2021-10-05 14:15 UTC, bertmeeuws commented on src/components/fileBrowser/FileTable.vue
> +            const goBack = () => {
When in grid view and a folder is empty you get the option to go back one page

2021-10-05 14:15 UTC, bertmeeuws commented on src/components/fileBrowser/MainActionButtons.vue
> +            @click="showCreateFileDialog = true"
Added a hover & duration

2021-10-05 14:15 UTC, bertmeeuws commented on src/components/fileBrowser/MainActionButtons.vue
> +            @click="showCreateFolderDialog = true"
Added a hover & duration

2021-10-05 14:16 UTC, bertmeeuws commented on src/components/fileBrowser/MainActionButtons.vue
> +                if (manualContactAdd.value.length >= 50) {
- Added max. char length in folders and it checks for '/'

2021-10-05 14:18 UTC, bertmeeuws commented
@JonasWijne Please sir, review my code

2021-10-06 08:58 UTC, JonasWijne requested changes

2021-10-06 08:58 UTC, JonasWijne commented on src/store/fileBrowserStore.ts
> +export const fileBrowserTypeView = ref<string>('LIST');
should be enum
```suggestion
export const fileBrowserTypeView = ref<View>('LIST');
```

2021-10-06 08:58 UTC, JonasWijne commented on src/store/fileBrowserStore.ts
> +    LIST,
```suggestion
    LIST = "LIST",
```

2021-10-07 11:06 UTC, merged