Dev edward#448
threefoldtech/twin_aydo pull request #458
Opened 2022-05-10 10:46 UTC by JorisBassle

Will push every once and a while for intermediate code review.
Don't delete the branch if PR is okay, I will continue with this one

2022-05-17 18:59 UTC, JonasWijne requested changes

2022-05-17 18:59 UTC, JonasWijne commented on src/store/fileBrowserStore.ts
> +// };
commented code should be deleted

2022-05-17 18:59 UTC, JonasWijne commented on src/components/ContactAdd.vue
> +        <div class='grid grid-cols-2'>
other files use " , what is the standard in this repo ?

2022-05-17 18:59 UTC, JonasWijne commented on src/services/fileService.ts
> +};
add a comment to the function which explains why we do this to stop any future confusion

2022-05-17 18:59 UTC, JonasWijne commented on src/store/authStore.ts
> +// };
For every line of code in comments a seal dies, this is true, many people know this
![image](https://user-images.githubusercontent.com/6184820/168887685-5fd3ab97-1f85-4367-969d-939d9bf1f382.png)

2022-05-17 18:59 UTC, JonasWijne commented on src/store/blockStore.ts
> +// };
![image](https://user-images.githubusercontent.com/6184820/168889531-1f49ac48-5abe-4845-8175-a6ef274d2336.png)

2022-05-17 18:59 UTC, JonasWijne commented on src/store/blockStore.ts
> +// };
![image](https://user-images.githubusercontent.com/6184820/168889344-90738450-ac3f-4d5d-ade3-e88ced4f3ad4.png)

2022-05-17 18:59 UTC, JonasWijne commented on src/store/fileBrowserStore.ts
> +// };
![image](https://user-images.githubusercontent.com/6184820/168889276-2cb7bbf6-2ccd-4be8-a55a-6f4a4014f0e2.png)

2022-05-17 18:59 UTC, JonasWijne commented on src/store/fileBrowserStore.ts
> +            // const id = await uploadTempFile(f);
![image](https://user-images.githubusercontent.com/6184820/168889175-017f6f58-def8-45cb-983c-a9b0e9e05ea3.png)

2022-05-17 19:02 UTC, JensMeire commented
A lot of seals died in cuz of this PR

2022-05-18 08:03 UTC, GillesMommerency commented
![image](https://user-images.githubusercontent.com/43674162/168989067-d8db3b84-bb48-4cb2-b00a-15bbb6e0fadb.png)

2022-06-07 12:31 UTC, JonasWijne commented on src/components/Dashboard/Post.vue
>      });
is this code still used ?

2022-06-07 12:31 UTC, JonasWijne requested changes

2022-06-07 12:31 UTC, JonasWijne commented on src/components/Dashboard/Post.vue
>      });
why http

2022-06-09 13:05 UTC, JorisBassle commented
@JonasWijne 
![image](https://user-images.githubusercontent.com/36887810/172853936-ff1976f0-49b0-4395-9e3f-feb57844294a.png)

2022-06-20 09:26 UTC, JonasWijne approved these changes

2022-06-20 09:49 UTC, merged