Dev joris#472
threefoldtech/twin_aydo pull request #503
Opened 2022-05-19 20:24 UTC by JorisBassle

![image](https://user-images.githubusercontent.com/36887810/169397593-93f4c233-2025-472d-a608-9b1819d12f94.png)

Also PR in the backend

2022-06-07 12:21 UTC, JonasWijne requested changes

2022-06-07 12:21 UTC, JonasWijne commented on src/components/GroupManagement.vue
> +        if ('roles' in contact) {
should be changed

2022-06-07 12:21 UTC, JonasWijne commented on src/components/GroupManagement.vue
> +        } else selectedUser.value.roles.push(Roles.MODERATOR);
no else in my codebase

2022-06-07 12:21 UTC, JonasWijne commented on src/components/GroupManagement.vue
> +        if ('roles' in contact) return contact.roles.includes(Roles.MODERATOR);
should be changed

2022-06-07 12:21 UTC, JonasWijne commented on src/store/chatStore.ts
> +    }
should be a switch and maybe move to a different function

2022-06-07 12:21 UTC, JonasWijne commented on src/store/socketStore.ts
>  import { handleRead, removeChat, usechatsActions } from './chatStore';
are these used ?

2022-06-10 16:05 UTC, JorisBassle commented on src/store/socketStore.ts
>  import { handleRead, removeChat, usechatsActions } from './chatStore';
yes
![image](https://user-images.githubusercontent.com/36887810/173106500-870dc24b-6235-44b5-b81e-917607832362.png)
![image](https://user-images.githubusercontent.com/36887810/173106576-be3b0be4-03bd-48c1-b46e-9b9397916017.png)

2022-06-14 11:25 UTC, JonasWijne approved these changes

2022-06-14 11:25 UTC, merged