Dev joris#534
threefoldtech/twin_aydo pull request #551
Opened 2022-07-14 17:49 UTC by JorisBassle

- Deleting chat also removes the contact from contact list. Contact list in the frontend should use 'contacts' from redis instead of chat list.
-  Deleting chat shows 'leaving group' should be 'Deleting chat'
-  Blocking user breaks whisper layout
-  Blocked contact gets unblocked after refreshing page
-  Should be able to add user to group by clicking on the whole list item instead of only the radio button
-  Add contact dialog showed up 2 times over each other
-  Adding a chat when you are still contacts with each other should not show the message 'request has been sent'
-  New group chat doesn't shows as 'unread chat' for the added user if there are no messages yet

2022-07-14 18:01 UTC, EdwardKerckhof requested changes

2022-07-15 07:14 UTC, JorisBassle commented on apps/backend/src/features/contact/contact.service.ts
> +            message.body.message = `You can start chatting again with ${newContact.id}`;
Why? You get the message in the following scenario:
- You send chat request to the other user and he accepts it
- You delete the chat but the other user keeps his chat
- You add the chat again with the same user

2022-07-15 07:18 UTC, JorisBassle commented on apps/backend/src/features/chat/chat.service.ts
> +            await this.syncNewChatWithAdmin({ adminLocation, chatId: chat.chatId });
yes, the code below is from syncNewChatWithAdmin. If the chat does not exist it creates a new one
![image](https://user-images.githubusercontent.com/36887810/179172375-7bc5d139-effc-47df-9d04-59dc85c639da.png)

2022-07-15 07:19 UTC, JorisBassle commented on apps/backend/src/features/contact/contact.service.ts
> +            message.body.message = `You can start chatting again with ${newContact.id}`;
or did you mean 'you can start chatting with ... again' ?

2022-07-15 08:01 UTC, EdwardKerckhof approved these changes

2022-07-15 08:01 UTC, merged