Read more is now shown based on amount of lines instead of amount of characters
threefoldtech/twin_aydo pull request #642
Opened 2022-08-05 11:58 UTC by Baertie

2022-08-05 11:59 UTC, Baertie commented
geen idee why ie gaf een conflict op de gitignore van de ds store terwijl het krak hetzelfde was. Change gehouden van development

2022-08-08 09:56 UTC, EdwardKerckhof requested changes

2022-08-08 09:56 UTC, EdwardKerckhof commented on apps/frontend/src/components/Dashboard/Post.vue
> +                        v-if="!readMore && amount_lines + 1 > 5"
move v-if to span so you do not have to vue directives bound to one element (v-if and v-for)

2022-08-08 12:50 UTC, EdwardKerckhof approved these changes

2022-08-08 12:50 UTC, merged